spring.application.name=HelloWorldWS
server.port=${PORT:80}

# Si MYSQLHOST no existe, usa localhost. Si MYSQLPORT no existe, usa 3306.
spring.datasource.url=jdbc:mysql://${MYSQLHOST:localhost}:${MYSQLPORT:3306}/${MYSQLDATABASE:werner_corp}?useSSL=false&serverTimezone=UTC
spring.datasource.username=${MYSQLUSER:root}
spring.datasource.password=${MYSQLPASSWORD:72.9.Rey.22}

# Configuración de Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
